name: Bob Says
on:
  workflow_dispatch:
    inputs: 
      what:
        description: 'What Should Bob Say?'
        required: true
        default: 'You are all terrible.'

jobs:
  just-these:
    runs-on: ubuntu-latest
    container: 
      image: viorelpe/ubuntools:latest
      
    steps:
    - name: install software
      run: |
        apt update
        apt install cowsay -y
  
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: saying [${{github.event.inputs.tools}}]
      run: |
        cowsay -f ./media/bob.cow "${{github.event.inputs.tools}}"
  
